# Jekyll Configuration for Distributed Systems Learning Repository
title: "Distributed Systems"
description: "A collection of distributed systems concepts, papers, and implementations"
baseurl: "/distributed_systems" # Repository name
url: "https://remidinishanth.github.io" # GitHub username
repository: "remidinishanth/distributed_systems"

# Build settings
markdown: kramdown
highlighter: rouge

# Minimal plugins for faster builds
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Collections for organizing content
collections:
  topics:
    output: true
    permalink: /:collection/:name/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.pdf"
  - _plugins
  - _scripts
  - PR_INSTRUCTIONS.md
  - JEKYLL_SETUP.md

# Include files that start with underscore
include:
  - _pages

# Kramdown settings - minimal for speed
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Navigation structure (will be auto-generated)
navigation:
  - title: "Home"
    url: "/"
  - title: "Topics"
    url: "/topics/"
