# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. You need to restart the server process to reflect your changes.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.

# The main title of your website. Appears in the browser tab and site header.
title: Distributed Systems Notes

# A short description of your website. Used by search engines.
description: My notes and projects for the Distributed Systems course.

# The Markdown processor to use. GFM is GitHub Flavored Markdown.
markdown: GFM

# List of Jekyll plugins to use.
plugins:
  - jekyll-relative-links

# Configuration for the jekyll-relative-links plugin.
# This automatically converts .md links to .html links.
relative_links:
  enabled:     true
  collections: true

# A list of files and folders to explicitly include in the site build.
# By default, Jekyll ignores README.md, so we must include it.
include:
  - README.md
  # You could include other files here too, like:
  # - LICENSE.md

# You can add more settings here as needed, like:
# author: Your Name
# email: your-email@example.com
